In [1]:
Output = '/Users/alexis/Library/CloudStorage/OneDrive-UniversityofNorthCarolinaatChapelHill/CEMALB_DataAnalysisPM/Projects/P1016. THC Adducts/P1016.3. Analyses/P1016.3.2. Cluster Analysis'
cur_date = "091926"

library(readxl)
library(tidyverse)
library(reshape2)
library(factoextra)
library(gridExtra)
library(ggrepel)
library(pheatmap)

# reading in files
genes_df = data.frame(read_excel("Input/Normalized_THC_Genes_091826.xlsx"))

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘reshape2’


The following object is masked from ‘package:tidyr’:

    smiths


Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa


Attaching package: ‘gridExtra’


The following object is masked from ‘package:dplyr’:

    combine

In [2]:
head(genes_df)

  ENSEMBL_ID      P1_Control P2_Control P3_Control P1_D8THC  P2_D8THC
1 ENSG00000000003 10.990138  10.896354  10.9276379 10.930041 10.945374
2 ENSG00000000419 10.671108  10.531594  10.6616560 10.691081 10.578911
3 ENSG00000000457  7.890700   7.964725   7.6763376  7.860145  7.982778
4 ENSG00000000460  9.729668   9.517500   9.6336101  9.693458  9.750993
5 ENSG00000000938  3.872863   2.615943   0.9029524  0.000000  4.733146
6 ENSG00000000971  3.490283   2.399225   3.2778192  2.410395  3.608611
  P3_D8THC  P1_D8THCq P2_D8THCq P3_D8THCq
1 10.916148 11.089867 10.968764 11.211598
2 10.815436 11.283165 10.709748 11.302640
3  8.055386  7.342812  7.676713  8.250021
4  9.816236  7.619355  9.240398  6.845747
5  4.157098  5.730201  2.582646  0.000000
6  3.540550  5.923764  4.582298  7.118193

This analysis will use PCA to explore if there are clusters of sample conditions that condensate, burn condition, and the time point. PCA will be run initially and the eigenvector values will be averaged within each sample condition to improve the visualization and elucidate any clusters that may arise.

The second part of this analysis will leverage hierarchical clustering to determine if specific biomarkers cluster. The gene expression analysis will be further stratified by time point (4 and 24hrs).
CHANGE!!
# Principal Component Analysis (PCA)

In [3]:
genes_df %>%
    pivot_longer(cols = 2:10, names_to = "Sample_ID", values_to = "Value") %>%
    separate(Sample_ID, sep = "_", c("Experiment", "Exposure"), remove = FALSE) %>%
    mutate(Sample_No = 1:(nrow(genes_df) * (ncol(genes_df)-1)))# %>%
    # # creating sample ids
    # unite("SampleID", c(colnames(mRNA_df)[c(3:7)]), remove = FALSE) %>%
    # pivot_wider(names_from = "Subject_ID", values_from = "Norm_ddCT") %>%
    # # keeping 4,24 hr time point, removing concentration of 5 and 1
    # filter(Time_Point %in% c(4,24), Concentration %in% c(25,NA)) %>%
    # column_to_rownames(var = "SampleID")

       ENSEMBL_ID      Sample_ID  Experiment Exposure Value     Sample_No
1      ENSG00000000003 P1_Control P1         Control  10.990138  1
2      ENSG00000000003 P2_Control P2         Control  10.896354  2
3      ENSG00000000003 P3_Control P3         Control  10.927638  3
4      ENSG00000000003 P1_D8THC   P1         D8THC    10.930041  4
5      ENSG00000000003 P2_D8THC   P2         D8THC    10.945374  5
6      ENSG00000000003 P3_D8THC   P3         D8THC    10.916148  6
7      ENSG00000000003 P1_D8THCq  P1         D8THCq   11.089867  7
8      ENSG00000000003 P2_D8THCq  P2         D8THCq   10.968764  8
9      ENSG00000000003 P3_D8THCq  P3         D8THCq   11.211598  9
10     ENSG00000000419 P1_Control P1         Control  10.671108 10
11     ENSG00000000419 P2_Control P2         Control  10.531594 11
12     ENSG00000000419 P3_Control P3         Control  10.661656 12
13     ENSG00000000419 P1_D8THC   P1         D8THC    10.691081 13
14     ENSG00000000419 P2_D8THC   P2         D8THC    10.578911 14
15     ENSG00000000419 P3_D8THC   P3         D8THC    10.815436 15
16     ENSG00000000419 P1_D8THCq  P1         D8THCq   11.283165 16
17     ENSG00000000419 P2_D8THCq  P2         D8THCq   10.709748 17
18     ENSG00000000419 P3_D8THCq  P3         D8THCq   11.302640 18
19     ENSG00000000457 P1_Control P1         Control   7.890700 19
20     ENSG00000000457 P2_Control P2         Control   7.964725 20
21     ENSG00000000457 P3_Control P3         Control   7.676338 21
22     ENSG00000000457 P1_D8THC   P1         D8THC     7.860145 22
23     ENSG00000000457 P2_D8THC   P2         D8THC     7.982778 23
24     ENSG00000000457 P3_D8THC   P3         D8THC     8.055386 24
25     ENSG00000000457 P1_D8THCq  P1         D8THCq    7.342812 25
26     ENSG00000000457 P2_D8THCq  P2         D8THCq    7.676713 26
27     ENSG00000000457 P3_D8THCq  P3         D8THCq    8.250021 27
28     ENSG00000000460 P1_Control P1         Control   9.729668 28
29     ENSG00000000460 P2_Control P2         Control   9.517500 29
30     ENSG00000000460 P3_Control P3         Control   9.633610 30
⋮      ⋮               ⋮          ⋮          ⋮        ⋮         ⋮
260008 ENSG00000283689 P1_D8THCq  P1         D8THCq   1.1829070 260008
260009 ENSG00000283689 P2_D8THCq  P2         D8THCq   0.0000000 260009
260010 ENSG00000283689 P3_D8THCq  P3         D8THCq   2.2259163 260010
260011 ENSG00000283691 P1_Control P1         Control  2.1416247 260011
260012 ENSG00000283691 P2_Control P2         Control  1.4383350 260012
260013 ENSG00000283691 P3_Control P3         Control  0.0000000 260013
260014 ENSG00000283691 P1_D8THC   P1         D8THC    0.0000000 260014
260015 ENSG00000283691 P2_D8THC   P2         D8THC    0.8479007 260015
260016 ENSG00000283691 P3_D8THC   P3         D8THC    0.9155984 260016
260017 ENSG00000283691 P1_D8THCq  P1         D8THCq   2.2663409 260017
260018 ENSG00000283691 P2_D8THCq  P2         D8THCq   0.0000000 260018
260019 ENSG00000283691 P3_D8THCq  P3         D8THCq   0.0000000 260019
260020 ENSG00000283696 P1_Control P1         Control  3.4902827 260020
260021 ENSG00000283696 P2_Control P2         Control  4.1081691 260021
260022 ENSG00000283696 P3_Control P3         Control  4.1315801 260022
260023 ENSG00000283696 P1_D8THC   P1         D8THC    4.6033277 260023
260024 ENSG00000283696 P2_D8THC   P2         D8THC    3.4057964 260024
260025 ENSG00000283696 P3_D8THC   P3         D8THC    4.2270500 260025
260026 ENSG00000283696 P1_D8THCq  P1         D8THCq   2.6043920 260026
260027 ENSG00000283696 P2_D8THCq  P2         D8THCq   2.3197041 260027
260028 ENSG00000283696 P3_D8THCq  P3         D8THCq   2.2259163 260028
260029 ENSG00000283697 P1_Control P1         Control  1.4363183 260029
260030 ENSG00000283697 P2_Control P2         Control  0.0000000 260030
260031 ENSG00000283697 P3_Control P3         Control  1.4540587 260031
260032 ENSG00000283697 P1_D8THC   P1         D8THC    1.4470391 260032
260033 ENSG00000283697 P2_D8THC   P2         D8THC    0.0000000 260033
260034 ENSG00000283697 P3_D8THC   P3         D8THC    0.0000000 260034
260035 ENSG00000283697 P1_D8THCq  P1         D8THCq   1.1829070 260035
260036 ENSG00000283697 P2_D8THCq  P2         D8THCq   0.0000000 260036
260037 ENSG00000283697 P3_D8THCq  P3         D8THCq   0.0000000 260037